// Discovery tier quest index — ages 6-10
// Auto-generated by gen_discovery.py

import type { CreateQuestInput } from '../../../types/quest.js';

import { discoveryWorkshopQuests } from './discovery-workshop.js';
import { discoveryAlchemistLabQuests } from './discovery-alchemist-lab.js';
import { discoveryCrystalCavernsQuests } from './discovery-crystal-caverns.js';
import { discoveryLivingForestQuests } from './discovery-living-forest.js';
import { discoveryLibraryEchoesQuests } from './discovery-library-echoes.js';
import { discoveryObservatoryQuests } from './discovery-observatory.js';
import { discoveryAncientRuinsQuests } from './discovery-ancient-ruins.js';
import { discoveryTradingPostQuests } from './discovery-trading-post.js';
import { discoveryArchitectsDomainQuests } from './discovery-architects-domain.js';
import { discoveryCodeForgeQuests } from './discovery-code-forge.js';
import { discoveryHealersSanctuaryQuests } from './discovery-healers-sanctuary.js';
import { discoveryHospitalQuests } from './discovery-hospital.js';
import { discoveryFarmQuests } from './discovery-farm.js';
import { discoveryLaboratoryQuests } from './discovery-laboratory.js';
import { discoveryExplorersMapQuests } from './discovery-explorers-map.js';
import { discoveryTimeRiftQuests } from './discovery-time-rift.js';
import { discoveryStormTowerQuests } from './discovery-storm-tower.js';
import { discoveryArenaQuests } from './discovery-arena.js';
import { discoveryShipyardQuests } from './discovery-shipyard.js';
import { discoveryMusicHallQuests } from './discovery-music-hall.js';
import { discoveryDigitalWorldQuests } from './discovery-digital-world.js';
import { discoverySpaceStationQuests } from './discovery-space-station.js';
import { discoveryDebateHallQuests } from './discovery-debate-hall.js';
import { discoveryGalleryQuests } from './discovery-gallery.js';
import { discoveryNewsroomQuests } from './discovery-newsroom.js';
import { discoveryTheaterQuests } from './discovery-theater.js';
import { discoveryMarketplaceQuests } from './discovery-marketplace.js';

export { discoveryWorkshopQuests } from './discovery-workshop.js';
export { discoveryAlchemistLabQuests } from './discovery-alchemist-lab.js';
export { discoveryCrystalCavernsQuests } from './discovery-crystal-caverns.js';
export { discoveryLivingForestQuests } from './discovery-living-forest.js';
export { discoveryLibraryEchoesQuests } from './discovery-library-echoes.js';
export { discoveryObservatoryQuests } from './discovery-observatory.js';
export { discoveryAncientRuinsQuests } from './discovery-ancient-ruins.js';
export { discoveryTradingPostQuests } from './discovery-trading-post.js';
export { discoveryArchitectsDomainQuests } from './discovery-architects-domain.js';
export { discoveryCodeForgeQuests } from './discovery-code-forge.js';
export { discoveryHealersSanctuaryQuests } from './discovery-healers-sanctuary.js';
export { discoveryHospitalQuests } from './discovery-hospital.js';
export { discoveryFarmQuests } from './discovery-farm.js';
export { discoveryLaboratoryQuests } from './discovery-laboratory.js';
export { discoveryExplorersMapQuests } from './discovery-explorers-map.js';
export { discoveryTimeRiftQuests } from './discovery-time-rift.js';
export { discoveryStormTowerQuests } from './discovery-storm-tower.js';
export { discoveryArenaQuests } from './discovery-arena.js';
export { discoveryShipyardQuests } from './discovery-shipyard.js';
export { discoveryMusicHallQuests } from './discovery-music-hall.js';
export { discoveryDigitalWorldQuests } from './discovery-digital-world.js';
export { discoverySpaceStationQuests } from './discovery-space-station.js';
export { discoveryDebateHallQuests } from './discovery-debate-hall.js';
export { discoveryGalleryQuests } from './discovery-gallery.js';
export { discoveryNewsroomQuests } from './discovery-newsroom.js';
export { discoveryTheaterQuests } from './discovery-theater.js';
export { discoveryMarketplaceQuests } from './discovery-marketplace.js';

/** All Discovery tier quests across every biome */
export const allDiscoveryQuests: CreateQuestInput[] = [
  ...discoveryWorkshopQuests,
  ...discoveryAlchemistLabQuests,
  ...discoveryCrystalCavernsQuests,
  ...discoveryLivingForestQuests,
  ...discoveryLibraryEchoesQuests,
  ...discoveryObservatoryQuests,
  ...discoveryAncientRuinsQuests,
  ...discoveryTradingPostQuests,
  ...discoveryArchitectsDomainQuests,
  ...discoveryCodeForgeQuests,
  ...discoveryHealersSanctuaryQuests,
  ...discoveryHospitalQuests,
  ...discoveryFarmQuests,
  ...discoveryLaboratoryQuests,
  ...discoveryExplorersMapQuests,
  ...discoveryTimeRiftQuests,
  ...discoveryStormTowerQuests,
  ...discoveryArenaQuests,
  ...discoveryShipyardQuests,
  ...discoveryMusicHallQuests,
  ...discoveryDigitalWorldQuests,
  ...discoverySpaceStationQuests,
  ...discoveryDebateHallQuests,
  ...discoveryGalleryQuests,
  ...discoveryNewsroomQuests,
  ...discoveryTheaterQuests,
  ...discoveryMarketplaceQuests,
];
