#!/usr/bin/env python3
"""Generate 1,000 Discovery tier quests across 27 biomes for Nexus Academy.
Ages 6-10. Singapore math CPA progression. Real education. No quiz language.
Run: python3 gen_discovery.py
"""
import os, re, textwrap

OUT = os.path.join(os.path.dirname(__file__), "src/data/quests/discovery")
os.makedirs(OUT, exist_ok=True)

def esc(s):
    return s.replace("\\","\\\\").replace("'","\\'").replace("\n","\\n")

SR_LABELS = {
    'interact':'Interaction','collect':'Collection','build':'Building',
    'craft':'Crafting','navigate':'Navigation','observe':'Observation',
    'teach':'Teaching','count':'Counting','match':'Matching',
    'sort':'Sorting','find':'Finding','mix':'Mixing',
    'measure':'Measurement','pattern':'Pattern','place':'Placement',
    'solve':'Solve','design':'Design','experiment':'Experiment',
    'balance':'Balance','decode':'Decode','diagnose':'Diagnose',
    'repair':'Repair','optimize':'Optimize','predict':'Prediction',
    'code':'Coding','explore':'Exploration','sequence':'Sequencing',
    'compare':'Comparison','transform':'Transform','protect':'Protection',
}

def sr(obj, inst):
    return f"{SR_LABELS.get(obj,'Activity')} task. {inst}"

def cr(inst):
    if len(inst)<=90: return inst
    for e in ['. ','! ','— ']:
        i=inst.find(e)
        if 0<i<100: return inst[:i+1].strip()
    t=inst[:85]; sp=t.rfind(' ')
    return (t[:sp] if sp>40 else t)+'.'

def S(obj, inst, hints, succ, fail):
    """Step shorthand."""
    return (obj, inst, hints, succ, fail)

def Q(slug, title, skills, desc, intro, steps, outro, mins=10):
    """Quest shorthand."""
    return (slug, title, skills, desc, intro, steps, outro, mins)

def fmt_step(i, s):
    obj,inst,hints,succ,fail = s
    lines = []
    lines.append("        {")
    lines.append(f"          index: {i},")
    lines.append(f"          instruction: '{esc(inst)}',")
    lines.append(f"          spokenInstruction: '{esc(inst)}',")
    lines.append(f"          screenReaderText: '{esc(sr(obj,inst))}',")
    lines.append(f"          companionRepeat: '{esc(cr(inst))}',")
    lines.append(f"          objectiveType: '{obj}',")
    hs = ", ".join(f"'{esc(h)}'" for h in hints)
    lines.append(f"          hints: [{hs}],")
    lines.append(f"          successResponse: '{esc(succ)}',")
    lines.append(f"          failureResponse: '{esc(fail)}',")
    lines.append("        },")
    return "\n".join(lines)

def fmt_quest(biome, q):
    slug,title,skills,desc,intro,steps,outro,mins = q
    qid = f"d-{biome}-{slug}"
    sk = ", ".join(f"'{s}'" for s in skills)
    st = "\n".join(fmt_step(i,s) for i,s in enumerate(steps))
    return f"""  {{
    id: '{qid}',
    title: '{esc(title)}',
    biome: '{biome}',
    masteryTier: 'discovery',
    skillsRequired: [],
    skillsTaught: [{sk}],
    content: {{
      description: '{esc(desc)}',
      companionIntro: '{esc(intro)}',
      steps: [
{st}
      ],
      companionOutro: '{esc(outro)}',
      estimatedMinutes: {mins},
    }},
  }}"""

def write_biome(slug, export_name, quests, comment):
    body = ",\n\n".join(fmt_quest(slug, q) for q in quests)
    content = f"""// Discovery tier quests — {comment}
// Ages 6-10: Companion is adventure partner, 2-4 steps, 2-3 skills per quest
// Singapore math CPA progression. Real education through gameplay.

import type {{ CreateQuestInput }} from '../../../types/quest.js';

export const {export_name}: CreateQuestInput[] = [
{body},
];
"""
    path = os.path.join(OUT, f"discovery-{slug}.ts")
    with open(path, 'w') as f:
        f.write(content)
    return len(quests)

# ============================================================
# QUEST DATA — 27 biomes × ~37 quests each = ~1,000 total
# ============================================================


# ============ BIOME 1: WORKSHOP (38 quests) ============
workshop_quests = [
Q('measure-beam','Measuring the Workshop Beam',['math.measurement','math.addition'],
  'A long wooden beam needs to be measured for a new shelf in the Workshop.',
  'Look at this beam! We need to figure out how long it is before we can build the shelf. Let us grab the measuring tape.',
  [S('measure','Use the measuring tape to find the length of the beam in centimeters.',
    ['Line the tape up with one end of the beam.','Read the number where the beam ends.'],
    'The beam is exactly right. Now we know what we are working with.',
    'The tape might not be lined up with the edge. Try starting from the very end of the beam.'),
   S('build','Cut two pieces from the beam so together they equal the measured length.',
    ['Think about how two shorter pieces can add up to the full length.','Check that both pieces fit on the shelf brackets.'],
    'Both pieces fit perfectly on the brackets. That is some precise work.',
    'The pieces do not quite fit. Measure each piece and compare their total to the original length.')],
  'That shelf is going to hold a lot of tools. Measuring carefully made all the difference.',10),

Q('area-workbench','Workbench Cover',['math.area','math.multiplication'],
  'The workbench surface is worn out and needs a new cover.',
  'This workbench has seen a lot of projects! We need to figure out how much material to cut for a new cover.',
  [S('measure','Measure the length and width of the workbench top in centimeters.',
    ['Measure one long side first, then one short side.','Write down both numbers before calculating.'],
    'Great measurements. Length and width — that is everything we need.',
    'Try measuring along the flat surface, from one edge all the way to the other.'),
   S('solve','Multiply the length by the width to find the area of the workbench.',
    ['Area is how much space the surface covers.','Think of it as rows of squares — length tells you how many columns, width tells you how many rows.'],
    'That is the right area! We know exactly how much covering material to cut.',
    'Imagine covering the surface with square tiles. Each row has as many tiles as the length, and there are as many rows as the width.'),
   S('craft','Cut the cover material to match the area and attach it to the workbench.',
    ['The material should cover the entire surface without hanging over.','Smooth it flat so there are no bumps.'],
    'The new cover fits like it was made for this bench — because it was!',
    'The cover seems a little off. Check that your area calculation matches the actual surface.')],
  'This workbench is ready for the next big project.',12),

Q('perimeter-fence','Workshop Yard Fence',['math.perimeter','math.addition'],
  'The workshop yard needs a fence to keep materials organized.',
  'Materials keep rolling around the yard. A fence would keep everything tidy. Let us figure out how much fencing we need.',
  [S('measure','Walk around the workshop yard and measure each side.',
    ['Count your steps along each wall.','There are four sides to measure.'],
    'All four sides measured. Now we can add them up.',
    'Make sure you measure every side, including the one by the storage shed.'),
   S('solve','Add all four side measurements together to find the perimeter.',
    ['Perimeter is the total distance around the outside.','Adding all the sides gives you the total length of fence needed.'],
    'That is exactly how much fencing we need. Nice adding!',
    'The total should include all four sides. Try adding them one at a time.'),
   S('build','Place fence posts at each corner and string the fence between them.',
    ['Put a post at every corner first.','Connect the posts with fence rails, one side at a time.'],
    'The yard is enclosed! No more runaway lumber.',
    'Check that every side has rails connecting the corner posts.')],
  'The yard looks so much more organized now. Perimeter calculations really help with building.',10),

Q('fraction-boards','Splitting Planks',['math.fractions','math.measurement'],
  'A woodworking project needs planks cut into equal fractions.',
  'We have long planks but the project needs smaller equal pieces. Time to divide them up!',
  [S('measure','Measure the full length of the plank.',
    ['Lay the plank flat and use the ruler.','Start measuring from one end.'],
    'We know the full length. Now we can figure out how to split it.',
    'Make sure the ruler starts at the very edge of the plank.'),
   S('solve','Figure out where to mark the plank to cut it into four equal pieces.',
    ['If you split something into 4 equal parts, each part is one quarter.','Divide the total length by 4 to find each piece length.'],
    'Those marks are evenly spaced. Each piece will be exactly one quarter of the whole plank.',
    'Each piece needs to be the same size. Try dividing the total length into four equal groups.'),
   S('craft','Cut along the marks and verify all four pieces are the same length.',
    ['Cut carefully right on each mark.','Stack the pieces to compare their lengths.'],
    'Four perfect quarters! Each one is exactly the same size.',
    'If the pieces are not equal, the marks might need adjusting. Measure each piece to check.')],
  'Fractions are not just numbers — they are how we split things fairly in the real world.',10),

Q('decimal-weights','Weighing Workshop Parts',['math.decimals','math.measurement'],
  'Small metal parts need to be weighed and sorted for a precision project.',
  'These parts look similar but weigh different amounts. The scale reads in decimals — let us sort them out.',
  [S('measure','Place each part on the scale and record its weight in grams.',
    ['The scale shows a number with a dot — that is a decimal.','Write down each weight carefully.'],
    'All the weights are recorded. Decimals tell us the exact amount, even between whole numbers.',
    'Wait for the scale to settle before reading the number.'),
   S('sort','Arrange the parts from lightest to heaviest using the decimal weights.',
    ['Compare the numbers before the dot first.','If those are the same, look at the number after the dot.'],
    'Perfectly sorted from lightest to heaviest!',
    'With decimals, 2.3 is less than 2.7 because 3 tenths is less than 7 tenths.'),
   S('place','Put each sorted part into the correct labeled bin.',
    ['Each bin has a weight range on its label.','Match the decimal weight to the right range.'],
    'Every part is in the right bin. The project can proceed with exactly the right components.',
    'Check the bin labels again — each one covers a small range of weights.')],
  'Decimals help us be precise when whole numbers are not enough.',10),

Q('multi-digit-gears','Gear Inventory Count',['math.multi-digit-addition','math.place-value'],
  'The Workshop received a large shipment of gears that need to be counted and cataloged.',
  'Look at all these gears! We need to count them up and add them to our inventory records.',
  [S('count','Count the gears in each of the three crates.',
    ['Group the gears by tens to count faster.','Keep track of each crate total separately.'],
    'Three crate counts are ready. Time to find the grand total.',
    'Try making groups of 10 gears and counting the groups.'),
   S('solve','Add all three crate totals together using column addition.',
    ['Line up the ones, tens, and hundreds columns.','Start adding from the ones column and carry if needed.'],
    'The grand total matches! Every gear is accounted for.',
    'When a column adds up to more than 9, carry the extra to the next column.'),
   S('build','Update the inventory board with the new total by adding it to the existing count.',
    ['The board shows the old total. Add the new gears to it.','This is multi-digit addition again — line up the place values.'],
    'The inventory board is current. The Workshop is fully stocked!',
    'Add the new shipment total to the number already on the board.')],
  'Keeping track of large numbers is easier when you organize by place value.',10),

Q('subtraction-offcuts','Using Up Offcuts',['math.multi-digit-subtraction','math.measurement'],
  'A long piece of timber needs to have sections removed, and we need to track the remaining length.',
  'We have a big piece of timber, but we only need certain sections. Let us figure out how much remains after each cut.',
  [S('measure','Measure the total length of the timber.',
    ['Use the long measuring tape.','Record the full length before any cuts.'],
    'Full length recorded. Now we know our starting point.',
    'Stretch the tape along the entire piece, end to end.'),
   S('solve','Subtract the first cut piece from the total to find the remaining length.',
    ['Write the bigger number on top and the smaller below.','Subtract column by column, borrowing if needed.'],
    'The remaining length is correct. Subtraction keeps us on track.',
    'When the top digit is smaller than the bottom, borrow from the next column over.'),
   S('solve','Subtract the second cut piece from the remaining length.',
    ['Start with the number you got from the first subtraction.','Subtract the new piece length from it.'],
    'We know exactly how much timber is left. No waste!',
    'Use the result from your first subtraction as the new starting number.')],
  'Multi-digit subtraction helps us track resources and avoid waste.',10),

Q('multiplication-tiles','Tiling the Workshop Floor',['math.multiplication','math.area'],
  'Part of the Workshop floor needs new tiles, arranged in neat rows and columns.',
  'The floor over here is getting rough. We can lay new tiles in a grid pattern — let us figure out how many we need.',
  [S('measure','Count how many tiles fit along the length and width of the area.',
    ['Lay tiles along one edge to count the length.','Do the same along the other edge for the width.'],
    'The grid dimensions are set — rows and columns ready to go.',
    'Count how many tiles fit in one row and how many rows there are.'),
   S('solve','Multiply the number of rows by the number of columns to find the total tiles needed.',
    ['Multiplication is a shortcut for adding the same number many times.','If there are 6 rows of 8 tiles, that is 6 times 8.'],
    'That is exactly the right number of tiles. Multiplication saves us from counting one by one.',
    'Think of it as groups — each row is a group with the same number of tiles.'),
   S('build','Lay the tiles in the grid pattern and verify the total matches your calculation.',
    ['Start from one corner and work row by row.','Keep the tiles snug together with no gaps.'],
    'The floor looks fantastic! Every tile is in place.',
    'If you end up with extra or missing tiles, double-check the grid dimensions.')],
  'Multiplication helps us figure out totals when things are arranged in equal groups or grids.',10),

Q('division-sharing','Sharing Workshop Supplies',['math.division','math.equal-groups'],
  'A delivery of craft supplies needs to be divided equally among the Workshop stations.',
  'A big box of supplies just arrived! Each station needs the same amount. Let us split them fairly.',
  [S('count','Count the total number of supply items in the box.',
    ['Group them by fives or tens for faster counting.','Keep a running total as you count.'],
    'Total counted. Now we know what we are dividing up.',
    'Organize the items into small groups first, then count the groups.'),
   S('solve','Divide the total equally among the four Workshop stations.',
    ['Division means splitting into equal groups.','Think: how many times does 4 go into the total?'],
    'Each station gets the same amount. Fair and square!',
    'Try dealing them out one at a time to each station, like dealing cards.'),
   S('place','Deliver the correct number of supplies to each station and handle any remainders.',
    ['If there are leftovers, those go in the shared supply cabinet.','Each station should have the exact same count.'],
    'All stations are stocked equally. The remainder is stored for everyone to share.',
    'Count each station pile to make sure they all match.')],
  'Division helps us share things equally — and remainders show what is left over.',10),

Q('coord-treasure','Workshop Treasure Map',['math.coordinates','math.grid-navigation'],
  'An old treasure map of the Workshop has coordinates marking where useful tools are hidden.',
  'I found this old map in the storage room! It has coordinates on it — numbers that tell us exact locations on a grid.',
  [S('observe','Study the grid map and identify how the coordinate system works.',
    ['The first number goes across (horizontal), the second goes up (vertical).','Find where the lines cross — that is the coordinate point.'],
    'The grid makes sense now. Each pair of numbers points to one exact spot.',
    'Think of coordinates like an address — one number for the street, one for the building.'),
   S('navigate','Follow the first set of coordinates to find a hidden tool.',
    ['Go across first, then up.','Count the grid lines carefully from the starting corner.'],
    'Found it! The coordinates led us right to it.',
    'Start at the corner where both numbers are zero, then count across, then up.'),
   S('navigate','Use the remaining coordinates to locate all hidden tools and mark them on your own map.',
    ['Plot each point by going across then up.','Double-check each location before marking it.'],
    'Every tool has been found! The coordinate system made this treasure hunt precise.',
    'If a location seems empty, re-count the grid lines from the origin.')],
  'Coordinates are like a secret code for locations — two numbers can describe any spot on a grid.',12),

Q('data-tool-survey','Workshop Tool Survey',['math.data-graphs','math.counting'],
  'The Workshop needs to know which tools are used most often to plan future orders.',
  'Which tools do we use the most? Let us survey the Workshop and make a chart to find out.',
  [S('collect','Visit each workstation and tally which tools are being used.',
    ['Make a mark for each tool you see in use.','Group your tallies by tool type.'],
    'Great data collection! Every workstation has been surveyed.',
    'Check behind the benches too — some tools might be in use out of sight.'),
   S('build','Create a bar graph showing how many of each tool type is in use.',
    ['Each bar represents one tool type.','The height of the bar shows how many are being used.'],
    'That bar graph tells the story clearly. Some tools are much more popular!',
    'Make sure each bar starts at zero and goes up to the right count.'),
   S('observe','Read the graph to identify the most-used and least-used tools.',
    ['The tallest bar shows the most popular tool.','Compare bar heights to see the differences.'],
    'Now we know exactly what to order more of. Data helps us make good decisions.',
    'Compare each bar to the others — which one reaches the highest?')],
  'Collecting data and showing it in a graph turns observations into useful information.',10),

Q('symmetry-design','Symmetrical Tool Rack',['math.symmetry','art.pattern-design'],
  'The Workshop needs a new tool rack with a symmetrical design so tools are easy to find.',
  'A tool rack with a symmetrical pattern means if you know one side, you know the other. Let us design one!',
  [S('design','Draw one half of the tool rack pattern on the grid.',
    ['Place hooks and shelves on the left side of the center line.','Make it practical — heavier tools on the bottom.'],
    'One half looks great. Now comes the mirror magic.',
    'Think about which tools you want where, and place them on one side.'),
   S('build','Mirror your design across the center line to complete the symmetrical rack.',
    ['Everything on the left should appear on the right, flipped like a mirror.','Count spaces from the center line to make sure each element is mirrored.'],
    'Perfect symmetry! Both sides are mirror images of each other.',
    'If something is 3 spaces left of center, its mirror should be 3 spaces right of center.'),
   S('craft','Build the rack and hang the tools according to the symmetrical design.',
    ['Follow your plan exactly.','Step back to check the symmetry looks right visually.'],
    'The finished rack is both beautiful and functional. Symmetry keeps things balanced.',
    'Compare left and right — each tool on one side should have a matching tool on the other.')],
  'Symmetry is everywhere in design — it creates balance and makes patterns easier to understand.',10),

Q('estimate-nails','Estimating Nail Quantities',['math.estimation','math.multiplication'],
  'A big building project needs lots of nails, and we need to estimate how many before ordering.',
  'This project needs a LOT of nails. Rather than counting every single one, let us estimate!',
  [S('count','Count the nails in one small handful.',
    ['Grab a comfortable handful and count them carefully.','This sample will help us estimate the whole box.'],
    'That is our sample size. Now we can use it to estimate the whole collection.',
    'Count each nail as you set it down separately.'),
   S('solve','Estimate the total by figuring out how many handfuls fit in the full container.',
    ['Look at how full the container is compared to your handful.','Multiply the handful count by the number of handfuls.'],
    'That is a solid estimate! Close enough to order the right amount.',
    'If about 10 handfuls fill the box, multiply your handful count by 10.'),
   S('compare','Compare your estimate to the actual count on the box label.',
    ['How close was your estimate to the actual number?','Being within a reasonable range is the goal of estimation.'],
    'Your estimate was in the right ballpark! Estimation saves time when exact counts are not needed.',
    'Estimates do not need to be perfect — they need to be close enough to be useful.')],
  'Estimation is a superpower — it helps us make quick, smart decisions without counting everything.',10),

Q('time-project','Workshop Project Timer',['math.time','math.elapsed-time'],
  'Different workshop projects take different amounts of time, and we need to schedule the day.',
  'We have three projects to finish today. Let us figure out the schedule so everything gets done.',
  [S('observe','Read the clock and note the current time.',
    ['Look at where the hour hand and minute hand are pointing.','The short hand shows the hour, the long hand shows minutes.'],
    'Current time noted. Now we can plan forward.',
    'Start with the short hand for the hour, then read the long hand for minutes.'),
   S('solve','Calculate when each project will finish if they take 45 minutes, 30 minutes, and 1 hour.',
    ['Add the minutes to the current time.','If minutes go past 60, that means a new hour.'],
    'The schedule is mapped out! We know exactly when each project wraps up.',
    'Start with the first project. Add 45 minutes to the current time. What time is it now?'),
   S('build','Create a timeline showing the start and end of each project on the Workshop schedule board.',
    ['Draw a line with time markers.','Mark the start and end of each project as blocks on the line.'],
    'The schedule board is complete. Everyone knows the plan!',
    'Each project block should start where the previous one ended.')],
  'Managing time means understanding how minutes and hours add up — an essential life skill.',10),

Q('money-supply-order','Workshop Supply Budget',['math.money','economics.budgets'],
  'The Workshop has a budget for new supplies and needs to figure out what to order.',
  'We have a set budget for supplies this month. Let us figure out what we can afford!',
  [S('observe','Read the supply catalog to find prices for the items we need.',
    ['Each item has a price listed next to it.','Note the prices including the cents after the decimal point.'],
    'Prices recorded. Now we can do the math.',
    'Look carefully at the price tags — dollars are before the dot, cents after.'),
   S('solve','Add up the prices of the items on our wish list and compare to the budget.',
    ['Add dollars and cents separately, then combine.','Start with the most important items.'],
    'The total is calculated! Let us see if it fits the budget.',
    'Line up the decimal points when adding money amounts.'),
   S('solve','If the total exceeds the budget, decide which items to remove to stay within it.',
    ['Subtract removed item prices from the total.','Keep the most essential items and save less urgent ones for next month.'],
    'Smart budgeting! We got what we needed and stayed within the budget.',
    'Which items are must-haves? Keep those and see if the rest fit.')],
  'Budgeting means making smart choices about what to spend — a skill that matters everywhere.',12),

Q('rounding-lumber','Rounding Lumber Lengths',['math.rounding','math.measurement'],
  'Lumber pieces have been measured precisely but need to be rounded for the cut list.',
  'These measurements have lots of detail, but the saw works best with rounded numbers. Let us round them.',
  [S('measure','Record the precise measurements of five lumber pieces.',
    ['Measure each piece to the nearest millimeter.','Write down the exact numbers.'],
    'Precise measurements recorded. Now we can round them for the saw.',
    'Include every digit the tape shows.'),
   S('solve','Round each measurement to the nearest ten centimeters.',
    ['Look at the ones digit — if it is 5 or more, round up.','If the ones digit is less than 5, round down.'],
    'All five measurements are rounded! The cut list is ready.',
    'For rounding to the nearest ten, focus on the digit in the ones place.'),
   S('compare','Compare the rounded lengths to the precise ones and note how much material changes.',
    ['Subtract the rounded from the original to see the difference.','Some round up, some round down — the differences are small.'],
    'Rounding keeps things practical while staying close to the real measurement.',
    'The difference between rounded and original should always be small — less than 5.')],
  'Rounding simplifies numbers while keeping them useful. Perfect for practical work.',10),

Q('pattern-bricks','Brick Pattern Wall',['math.patterns','art.pattern-design'],
  'A decorative brick wall in the Workshop needs to follow a repeating color pattern.',
  'This wall will look amazing with a repeating pattern! Let us design it and lay the bricks.',
  [S('pattern','Identify the repeating pattern in the first row of bricks already placed.',
    ['Look at the colors — do they repeat?','Find where the pattern starts over.'],
    'The pattern unit is clear! Now we can extend it.',
    'A pattern is a sequence that repeats. Look for the point where it starts again.'),
   S('build','Continue the pattern for three more rows, keeping the sequence consistent.',
    ['Each row should follow the same color sequence.','Check your work by reading the pattern aloud.'],
    'The pattern continues perfectly. The wall is really taking shape!',
    'If you lose track, go back to the start of the row and check each brick against the pattern.'),
   S('predict','Predict what the 25th brick in the sequence will be without laying all of them.',
    ['The pattern repeats every few bricks.','Divide 25 by the pattern length to find where you land.'],
    'Correct! Knowing the pattern length lets you predict any position. That is powerful.',
    'If the pattern is 3 bricks long, the 25th brick is the same as... think about remainders.')],
  'Patterns are not just pretty — they let us predict what comes next without checking every single item.',10),

Q('graph-temperature','Workshop Temperature Log',['math.data-graphs','science.measurement'],
  'The Workshop temperature needs to be tracked throughout the day for the paint-drying project.',
  'Some paints dry better at certain temperatures. Let us record the Workshop temperature and make a graph.',
  [S('measure','Read the thermometer every hour and record the temperature.',
    ['The number next to the liquid line is the temperature.','Record the time and temperature together.'],
    'Four readings are in. Enough data to see a trend.',
    'Look at where the red line stops on the thermometer scale.'),
   S('build','Plot the temperatures on a line graph with time on the bottom and temperature on the side.',
    ['Put a dot for each reading at the right time and temperature.','Connect the dots with straight lines.'],
    'The line graph shows exactly how the temperature changed over the day!',
    'Each dot needs two coordinates — the time (across) and the temperature (up).'),
   S('observe','Read the graph to find the warmest time and coolest time.',
    ['The highest point on the line is the warmest reading.','The lowest point is the coolest.'],
    'Now we know the best time to start painting! Graphs turn data into decisions.',
    'Follow the line — where does it peak? Where does it dip?')],
  'Line graphs show how something changes over time — essential for tracking and planning.',10),

Q('place-value-parts','Parts Sorting by Place Value',['math.place-value','math.comparison'],
  'Bins of small parts have quantities written on them and need to be organized by amount.',
  'These bins are all jumbled up! The numbers on them tell us how many parts are inside. Let us sort them.',
  [S('observe','Read the multi-digit numbers on each bin label.',
    ['Each digit has a different value depending on its position.','The leftmost digit is worth the most.'],
    'All the numbers are read. Time to figure out which is which.',
    'In the number 347, the 3 means 300, the 4 means 40, and the 7 means 7.'),
   S('sort','Arrange the bins from smallest number to largest.',
    ['Compare the hundreds digit first.','If the hundreds are the same, compare the tens.'],
    'Perfectly sorted! The bins go from fewest parts to most.',
    'When comparing numbers, start from the left. The first digit that differs tells you which is bigger.'),
   S('compare','Use greater-than and less-than to describe how neighboring bins compare.',
    ['The open end of the sign faces the bigger number.','Think of it as an alligator mouth — it always wants the bigger number.'],
    'All the comparisons are labeled. Anyone can see the order at a glance.',
    'The symbol points toward the smaller number and opens toward the bigger one.')],
  'Place value is the secret to understanding big numbers — each digit position multiplies by ten.',10),

Q('parallel-lines','Straight and Parallel Shelves',['math.geometry-lines','math.measurement'],
  'New shelves need to be installed perfectly parallel to each other on the Workshop wall.',
  'Crooked shelves mean sliding tools! These need to be perfectly parallel — the same distance apart everywhere.',
  [S('measure','Measure the distance between the two existing shelf brackets at both ends.',
    ['If both ends measure the same distance, the shelves are parallel.','Even a small difference means they are not parallel.'],
    'Both measurements match — those existing shelves are truly parallel.',
    'Measure at the far left and far right. The two distances should be identical.'),
   S('build','Install new brackets for a third shelf, keeping it parallel to the existing ones.',
    ['Measure the same distance down from the shelf above at both ends.','Use a level to double-check.'],
    'The new brackets are perfectly positioned. Parallel lines never meet, no matter how far they go.',
    'If the distances from the shelf above are not equal on both sides, adjust until they match.'),
   S('observe','Check all three shelves by placing a long straight edge across them.',
    ['The straight edge should touch all three shelf fronts evenly.','Any gaps mean the shelves are not aligned.'],
    'Three perfectly parallel shelves! Tools will stay right where you put them.',
    'Look for gaps between the straight edge and any shelf front.')],
  'Parallel lines keep the same distance apart forever. That is why parallel shelves keep things from sliding.',10),

Q('angle-brackets','Angle Bracket Assembly',['math.angles','math.measurement'],
  'Metal angle brackets need to be set at specific angles for a support structure.',
  'These brackets come in different angles. We need to find the right ones and set them correctly.',
  [S('measure','Use the protractor to measure the angle of each bracket in the collection.',
    ['Place the protractor flat with the center on the angle point.','Read the degree number where the bracket arm crosses the scale.'],
    'Angles measured! Now we know what we have to work with.',
    'The protractor center goes on the corner of the angle, one arm along the baseline.'),
   S('find','Select the brackets that match the required 90-degree right angles.',
    ['A right angle looks like a perfect corner, like the corner of a book.','On the protractor, 90 degrees is straight up from the baseline.'],
    'Right angle brackets found! These make the strongest corners.',
    'A right angle is exactly one quarter of a full turn — like the corner of a square.'),
   S('build','Assemble the support structure using the correct angle brackets at each joint.',
    ['Each joint needs the right angle to hold the weight properly.','Tighten each bracket firmly.'],
    'The structure is solid! The right angles at every joint make it incredibly strong.',
    'If the structure feels wobbly, check that each bracket is truly at 90 degrees.')],
  'Angles determine how strong a structure is. Right angles create the most stable corners.',10),

Q('fraction-paint','Mixing Paint Colors',['math.fractions','art.color-wheel'],
  'Different paint colors need to be mixed using exact fractional amounts for the right shade.',
  'We need a very specific shade for this project. The recipe calls for fractions of each color.',
  [S('measure','Measure one-half cup of blue paint using the measuring cup.',
    ['The one-half line is exactly in the middle of the cup.','Pour slowly and stop right at the line.'],
    'Perfect half cup of blue. Fractions help us be precise with amounts.',
    'Find the line marked 1/2 on the measuring cup.'),
   S('measure','Add one-quarter cup of white paint to the blue.',
    ['One quarter is half of one half.','The 1/4 line is lower than the 1/2 line.'],
    'One quarter added. The color is already starting to change.',
    'A quarter cup is less than a half cup. Look for the line below the halfway mark.'),
   S('mix','Stir the mixture and compare the resulting shade to the target color swatch.',
    ['Mix thoroughly until the color is uniform.','Hold the swatch next to your mixture to compare.'],
    'That shade matches perfectly! Fractions give us precise control over mixing.',
    'If the color is too dark, a bit more white will lighten it. If too light, a touch more blue.')],
  'Fractions are everywhere in crafting — they help us get exact amounts for perfect results.',10),

Q('bar-model-nails','Bar Model for Nail Problem — Journal Page',['math.bar-model','math.addition'],
  'A crumbling workshop journal page shows bar models — diagrams that turn tricky problems into pictures. The page describes using bar models to figure out supply needs.',
  'Look — an old journal page fell out from behind the tool rack! It shows these rectangle diagrams called bar models. The Founders used these to solve supply problems. Let us try their method.',
  [S('observe','Study the bar model on the journal page and understand how it represents the problem.',
    ['The bar is split into parts that represent different amounts.','The whole bar represents the total.'],
    'The bar model makes the problem visual! You can see how the parts relate to the whole.',
    'Think of the bar as a real bar of material. The sections show how it is divided.'),
   S('solve','Draw your own bar model to represent the problem: if we have 45 short nails and 38 long nails, how many total?',
    ['Draw one bar split into two sections — one for 45 and one for 38.','The total length of the bar represents the answer.'],
    'Your bar model shows it clearly — two parts combine into one whole. Adding gives the total.',
    'Put the two amounts side by side in the bar. Together they make the total.'),
   S('solve','Use the bar model to solve a related problem: if we need 120 nails total and have 75, how many more do we need?',
    ['Draw the total bar as 120. Mark off the 75 we have.','The gap is the unknown — how many more we need.'],
    'The bar model shows the gap! Subtraction fills in what is missing. The Founders were clever.',
    'The difference between the whole and the part you have is the part you need.')],
  'Bar models turn word problems into pictures. This journal method from the Founders still works perfectly.',12),

Q('line-plot-screws','Screw Length Line Plot',['math.data-graphs','math.measurement'],
  'A collection of screws needs to be measured and displayed on a line plot.',
  'We have a bunch of screws that look different lengths. Let us measure them all and make a line plot!',
  [S('measure','Measure each screw length to the nearest quarter inch.',
    ['Line up the screw with the ruler.','Find the closest quarter-inch mark.'],
    'All screws measured to the nearest quarter inch. Good precision!',
    'Quarter-inch marks divide each inch into four equal parts.'),
   S('build','Create a line plot with X marks above each measurement on a number line.',
    ['Draw a number line with quarter-inch increments.','Put an X above the matching length for each screw.'],
    'The line plot shows the distribution clearly! Some lengths are much more common.',
    'Each X represents one screw. Stack them above the same number if multiple screws match.'),
   S('observe','Identify the most common screw length and the range of all lengths.',
    ['The tallest stack of X marks shows the most common length.','The range is the difference between the longest and shortest.'],
    'You can read the whole story from the plot — most common, range, and everything in between.',
    'Count which column has the most X marks. That length appears the most.')],
  'Line plots reveal patterns in measurement data that you cannot see by looking at a pile of screws.',10),

Q('volume-box','Box Volume for Storage',['math.volume','math.multiplication'],
  'Storage boxes need to be built with enough volume to hold specific amounts of Workshop supplies.',
  'We need boxes that hold a specific amount. Volume tells us how much space is inside — let us calculate it.',
  [S('measure','Measure the length, width, and height of the space the box needs to fill.',
    ['Length goes front to back, width goes side to side, height goes bottom to top.','Use the same units for all three measurements.'],
    'Three dimensions measured. Volume needs all three.',
    'Each measurement goes in a different direction — you need all three to find volume.'),
   S('solve','Multiply length times width times height to calculate the volume.',
    ['Volume is 3D — length times width gives the base area, then multiply by height.','Think of it as layers of flat tiles stacked up.'],
    'The volume is calculated! We know exactly how much the box can hold.',
    'Multiply two of the numbers first, then multiply the result by the third.'),
   S('build','Construct the box and verify it fits the required supplies inside.',
    ['Cut the panels to the right dimensions.','Assemble with the measured sides matching your plan.'],
    'The supplies fit perfectly! Volume calculations prevent guessing.',
    'If the box is too small, check each dimension against your measurements.')],
  'Volume measures three-dimensional space. Length times width times height — three numbers, one answer.',12),

Q('equivalent-fractions','Equivalent Fraction Gears',['math.equivalent-fractions','math.fractions'],
  'Gear wheels in the Workshop demonstrate equivalent fractions — different-sized pieces that represent the same amount.',
  'These gears are different sizes but some turn at the same rate. That is like equivalent fractions — different numbers, same value.',
  [S('observe','Compare gears with different numbers of teeth and notice which ones mesh the same way.',
    ['A gear with 2 out of 4 teeth colored is the same fraction as 1 out of 2.','Look for gears where the same proportion is colored.'],
    'Those gears represent equivalent fractions! Half is half, whether it is 1/2 or 2/4 or 3/6.',
    'Compare how much of each gear is colored — if the same amount is shaded, they are equivalent.'),
   S('match','Match pairs of gears that represent equivalent fractions.',
    ['Multiply or divide both the top and bottom number by the same amount.','If you can simplify one fraction to get the other, they are equivalent.'],
    'All pairs matched! Equivalent fractions look different but mean the same thing.',
    '2/4 simplifies to 1/2 because both 2 and 4 divide by 2. That makes them equivalent.'),
   S('build','Create a gear with 8 teeth that shows a fraction equivalent to 3/4.',
    ['3/4 means 3 out of 4 parts. How many out of 8 is the same proportion?','Multiply both 3 and 4 by the same number to get a denominator of 8.'],
    '6/8 — six teeth colored out of eight. That is exactly the same amount as 3/4.',
    'Multiply 3 by 2 and 4 by 2. What fraction do you get?')],
  'Equivalent fractions are different names for the same amount. The gears prove it mechanically!',10),

Q('mixed-numbers','Mixed Number Measurements',['math.mixed-numbers','math.measurement'],
  'Workshop materials are measured in mixed numbers — whole parts plus fractions.',
  'Some of these boards are between whole number lengths. We use mixed numbers to describe them exactly.',
  [S('measure','Measure three boards that fall between whole-number lengths.',
    ['A board might be between 3 and 4 feet long — it is 3 and something.','Read the fraction part on the ruler after the whole number.'],
    'Mixed numbers captured! They show the whole feet plus the extra fraction.',
    'Find the whole number first, then figure out the fraction of the remaining part.'),
   S('solve','Add two of the mixed-number measurements together.',
    ['Add the whole numbers first, then add the fractions.','If the fractions add to more than one whole, carry it over.'],
    'Mixed number addition complete! The total makes sense for combined lengths.',
    'Add the whole parts: 3 + 2 = 5. Then add the fractions: 1/4 + 2/4 = 3/4. Total: 5 and 3/4.'),
   S('compare','Compare the mixed numbers to determine which board is longest.',
    ['Compare the whole number parts first.','If the whole parts are the same, compare the fractions.'],
    'Longest board identified! Mixed numbers make comparing between whole numbers easy.',
    'If one is 3 and 1/2 and another is 3 and 3/4, compare the fractions since the wholes are equal.')],
  'Mixed numbers handle those in-between measurements that whole numbers cannot capture.',10),

Q('number-line-fractions','Fraction Number Line',['math.fractions','math.number-line'],
  'A special Workshop ruler needs fraction marks added between the whole numbers.',
  'This ruler only has whole numbers on it. We need to add fraction marks so we can measure precisely.',
  [S('observe','Look at the space between 0 and 1 on the ruler and plan where fractions go.',
    ['One-half goes right in the middle.','Quarters divide each half in half again.'],
    'The plan is clear — the space between whole numbers gets divided into equal parts.',
    'If you fold the space in half, the crease is at one-half. Fold again for quarters.'),
   S('place','Mark one-half, one-quarter, and three-quarters between 0 and 1.',
    ['1/2 is right in the center.','1/4 is halfway between 0 and 1/2. 3/4 is halfway between 1/2 and 1.'],
    'The fraction marks are perfectly placed! Each one divides the space further.',
    'Check that the spaces between adjacent marks are equal.'),
   S('place','Extend the fraction marks between 1 and 2, and between 2 and 3.',
    ['The same pattern repeats in every whole number interval.','1 and 1/4 is the same distance past 1 as 1/4 is past 0.'],
    'The ruler is complete with fraction marks everywhere! This tool can measure anything precisely.',
    'Each whole number section gets the same fraction marks in the same positions.')],
  'Number lines show exactly where fractions live — between the whole numbers, in precise positions.',10),

Q('multi-step-project','Workshop Multi-Step Project',['math.multi-step-problems','math.operations'],
  'A complex Workshop project requires multiple mathematical operations to plan correctly.',
  'This project has several parts that each need calculation. Let us work through it step by step.',
  [S('solve','Calculate the total materials needed: 6 shelves each requiring 8 brackets.',
    ['Multiplication finds the total when groups are equal.','6 groups of 8 means 6 times 8.'],
    'Total brackets calculated! Step one complete.',
    'Think: 6 shelves, each with 8 brackets. How many brackets altogether?'),
   S('solve','The supplier sells brackets in packs of 10. How many packs do we need to buy?',
    ['Divide the total by 10 to see how many full packs.','If there is a remainder, you need one more pack.'],
    'Pack count determined! We round up because you cannot buy part of a pack.',
    'If you need 48 and packs have 10, 4 packs give 40 — not enough. You need 5 packs.'),
   S('solve','Calculate the total cost if each pack costs 12 gold coins and find the change from 100 gold.',
    ['Multiply the number of packs by the price per pack.','Subtract the total cost from 100 to find the change.'],
    'The full calculation is done — quantity, packs, cost, and change. Multi-step problems break big questions into small ones.',
    'Take it one step at a time. Packs times price equals total cost. Then subtract from your budget.')],
  'Real projects need multiple math steps. Breaking a big problem into smaller ones makes it manageable.',12),

Q('right-angle-check','Right Angle Quality Check — Journal Page',['math.angles','math.geometry-shapes'],
  'An old workshop journal describes how the Founders used right angles to check the quality of every piece they built. The page has sketches of angle-checking tools.',
  'This journal page is from one of the original Workshop builders! They checked every corner with a right angle tool. No wonder their work lasted so long. Let us learn their method.',
  [S('observe','Read the journal page to understand how the Founders verified right angles.',
    ['The page shows a simple L-shaped tool pressed into corners.','If the tool fits perfectly, the angle is exactly 90 degrees.'],
    'The Founders knew that right angles make strong, square corners. Smart builders.',
    'Look at the sketches — the checking tool is pressed into each corner of the finished work.'),
   S('measure','Use a right-angle checker to test every corner of the latest Workshop project.',
    ['Press the checker into each corner.','If there is a gap, the angle is not 90 degrees.'],
    'All corners checked! Some are perfect, some need adjusting.',
    'Rotate the checker to fit into each corner. A gap means the angle is off.'),
   S('repair','Adjust any corners that are not true right angles until the checker fits perfectly.',
    ['Gently tap the joint until the checker slides in with no gap.','Small adjustments make a big difference.'],
    'Every corner is a perfect right angle now. The Founders would be proud!',
    'If the gap is on one side, the angle is too wide. If the checker cannot fit, it is too narrow.')],
  'Right angles are the foundation of solid construction. The Founders knew that, and now so do we.',12),

Q('elapsed-time-project','Project Time Tracking',['math.elapsed-time','math.subtraction'],
  'Workshop projects need time tracking to improve future planning.',
  'How long do projects actually take? Let us track the time on this one so we can plan better next time.',
  [S('observe','Note the start time of the project on the Workshop clock.',
    ['Read the hour and minutes carefully.','Write it down so we do not forget.'],
    'Start time recorded. The clock is running!',
    'Check both the hour hand and minute hand to get the exact time.'),
   S('observe','Note the finish time when the project is completed.',
    ['Read the clock again when the last piece is in place.','Write the finish time next to the start time.'],
    'Finish time recorded! Now we can calculate the duration.',
    'Same as before — read both hands of the clock.'),
   S('solve','Calculate the elapsed time by finding the difference between start and finish.',
    ['Subtract the start time from the finish time.','Count forward from start to finish if subtraction feels tricky.'],
    'We know exactly how long the project took! This data helps us plan future work.',
    'Count forward hour by hour from the start time, then add the remaining minutes.')],
  'Tracking elapsed time helps us plan better. The more data we collect, the more accurate our estimates become.',10),

Q('pictograph-materials','Material Usage Pictograph',['math.data-graphs','math.counting'],
  'The Workshop tracks which materials get used each week to plan restocking.',
  'Each week we use different amounts of wood, metal, and fabric. A pictograph makes it easy to see at a glance.',
  [S('count','Count how many units of each material type were used this week.',
    ['Check the material logs for wood, metal, and fabric totals.','Round to the nearest 5 for the pictograph.'],
    'Material counts are in! Time to turn numbers into pictures.',
    'Add up each material type separately.'),
   S('build','Create a pictograph where each symbol represents 5 units of material.',
    ['Draw a small icon for each material type.','If we used 20 units of wood, draw 4 wood icons.'],
    'The pictograph is colorful and clear! Each icon stands for 5 units.',
    'Divide each total by 5 to know how many icons to draw.'),
   S('observe','Use the pictograph to compare usage and predict next week needs.',
    ['Which material has the most icons?','If usage is similar each week, next week will need about the same.'],
    'The pictograph tells the whole story. We know what to order more of!',
    'Count the icons for each material. More icons means more usage.')],
  'Pictographs use pictures instead of numbers to show data — quick to read and easy to understand.',10),

Q('factor-pairs','Factor Pair Tool Boxes',['math.factors','math.multiplication'],
  'Tools need to be organized into rectangular box arrangements, exploring different factor pairs.',
  'We have 24 tools to organize into a rectangular box grid. How many different arrangements can we make?',
  [S('solve','Find all the pairs of numbers that multiply to make 24.',
    ['Start with 1 times 24, then try 2 times something.','Keep going until the numbers start repeating.'],
    'All factor pairs found! 1x24, 2x12, 3x8, 4x6 — each one works.',
    'Ask: does 2 go into 24 evenly? Does 3? Does 4? Each one that works gives a factor pair.'),
   S('build','Arrange 24 tool tokens in each of the factor pair rectangles.',
    ['For 3x8, make 3 rows of 8.','For 4x6, make 4 rows of 6.'],
    'Every arrangement uses all 24 tools! Different shapes, same total.',
    'Each arrangement should use exactly 24 items with no leftovers.'),
   S('compare','Decide which arrangement best fits the available shelf space.',
    ['Measure the shelf and compare to each rectangle shape.','A tall narrow arrangement fits different spaces than a wide short one.'],
    'The best fit is chosen! Factor pairs give us options for organizing the same quantity.',
    'Compare the dimensions of each arrangement to the shelf dimensions.')],
  'Factor pairs show all the different ways to arrange the same quantity into rectangles.',10),

Q('perimeter-vs-area','Perimeter vs Area Challenge',['math.perimeter','math.area'],
  'Two garden plots look different but might have the same perimeter or area. Let us investigate.',
  'Here are two different shaped plots. One is long and thin, the other is more square. Do they have the same perimeter? Same area?',
  [S('measure','Measure all sides of both plots and calculate each perimeter.',
    ['Add all the side lengths for each plot.','Write down both perimeters to compare.'],
    'Perimeters calculated! Now let us see if they match or differ.',
    'Remember, perimeter is the total distance all the way around.'),
   S('solve','Calculate the area of each plot by multiplying length times width.',
    ['For a rectangle, area equals length times width.','Calculate each one separately.'],
    'Areas calculated! Interesting — same perimeter does not mean same area.',
    'Multiply the long side by the short side for each plot.'),
   S('compare','Compare the perimeters and areas. Can shapes have the same perimeter but different area?',
    ['Two shapes can share a perimeter but enclose different amounts of space.','The more square a rectangle is, the more area it has for a given perimeter.'],
    'Great discovery! Perimeter and area measure different things. Same perimeter can give different areas.',
    'Place both results side by side. Are the perimeters equal? Are the areas?')],
  'Perimeter measures the fence around something. Area measures the ground inside. They behave differently!',12),

Q('skip-counting-inventory','Skip Counting Inventory',['math.skip-counting','math.multiplication'],
  'Boxes of parts are stacked in groups, and skip counting makes the inventory fast.',
  'Counting one by one would take forever! These boxes are in groups, so we can skip count.',
  [S('count','Skip count by 5s to total the boxes in the first section.',
    ['5, 10, 15, 20... each group adds 5 more.','Touch each group as you count.'],
    'Skip counting by 5s is so much faster than counting one by one!',
    'Start at 5 and add 5 each time you touch a new group.'),
   S('count','Skip count by 3s to total the parts in the second section.',
    ['3, 6, 9, 12... each group adds 3 more.','Keep the rhythm steady.'],
    'Skip counting by 3s works just the same way. Different number, same idea.',
    'Add 3 each time: 3, 6, 9, 12, 15...'),
   S('compare','Compare skip counting results to verify: does skip counting by 5s ten times equal regular multiplication?',
    ['Skip counting by 5s ten times gives 50. Is that the same as 5 times 10?','Multiplication IS skip counting!'],
    'They are the same! Skip counting is just multiplication in action.',
    'Count by 5s ten times and compare to 5 times 10. What do you notice?')],
  'Skip counting is multiplication made physical. Every time you skip count, you are multiplying.',10),

Q('unit-conversion','Converting Measurements',['math.unit-conversion','math.multiplication'],
  'Workshop plans use different measurement units and we need to convert between them.',
  'These plans are in feet but our rulers are in inches! We need to convert. There are 12 inches in every foot.',
  [S('solve','Convert 3 feet to inches by multiplying by 12.',
    ['Each foot equals 12 inches.','3 feet times 12 inches per foot gives the total inches.'],
    '36 inches! Multiplying by the conversion factor switches the units.',
    '3 groups of 12 inches. What is 3 times 12?'),
   S('solve','Convert 5 feet 6 inches to total inches.',
    ['First convert the 5 feet to inches, then add the extra 6 inches.','5 times 12 plus 6.'],
    '66 inches total! Breaking it into steps makes it easy.',
    'Convert feet to inches first (5 times 12 = 60), then add the remaining 6 inches.'),
   S('measure','Measure a board in inches and then express it in feet and inches.',
    ['Divide the total inches by 12 to get feet.','The remainder is the leftover inches.'],
    'Converting both ways! Division undoes multiplication when switching back.',
    'How many groups of 12 fit in your number? That is the feet. What is left over is the inches.')],
  'Unit conversion is just multiplication and division with a conversion factor. The number changes, but the real length stays the same.',10),

Q('number-patterns','Number Pattern Machine',['math.patterns','math.operations'],
  'The Workshop has a mysterious machine with a number pattern display. Figuring out the pattern reveals the unlock code.',
  'This machine has a number sequence on it, but some numbers are missing. If we figure out the pattern, we can unlock it!',
  [S('observe','Study the visible numbers in the sequence and look for a pattern.',
    ['What happens between each number?','Does it go up by the same amount each time?'],
    'A pattern is emerging! Each number relates to the next one in a specific way.',
    'Write out the numbers and look at the gaps between them.'),
   S('predict','Predict the next three numbers in the sequence.',
    ['Apply the pattern rule to extend the sequence.','Check: does your predicted number follow the same rule?'],
    'Your predictions match! The pattern rule works for every step.',
    'Whatever you do to get from one number to the next, do it again for the next one.'),
   S('solve','Enter the missing numbers to unlock the machine.',
    ['Place each predicted number in its slot.','The machine activates if all numbers follow the rule.'],
    'The machine whirs to life! Pattern recognition just opened a door to something new.',
    'If the machine does not activate, re-check the pattern between the known numbers.')],
  'Patterns are the language of mathematics. Once you see the rule, you can predict anything.',10),

Q('comparing-fractions','Fraction Comparison Weights',['math.fractions','math.comparison'],
  'Balance weights labeled with fractions need to be compared to find which is heavier.',
  'These weights have fractions on them instead of regular numbers. Which fraction represents more? The balance will tell us.',
  [S('observe','Place two fraction weights on the balance and see which side drops.',
    ['The heavier side drops down.','The fraction on the heavier weight represents a larger amount.'],
    'The balance shows which fraction is larger! Physical comparison makes it clear.',
    'Watch which side of the balance goes down — that side has the bigger fraction.'),
   S('solve','Compare two fractions with different denominators by finding a common denominator.',
    ['Find a number that both denominators go into evenly.','Convert both fractions to use that common denominator, then compare numerators.'],
    'Common denominators let you compare fractions by just looking at the numerators!',
    'For 2/3 and 3/4, both 3 and 4 go into 12. Convert both to twelfths, then compare.'),
   S('sort','Arrange five fraction weights from lightest to heaviest.',
    ['Convert each to a common denominator, or compare pairs using the balance.','Put confirmed lighter ones to the left.'],
    'All five are in order! Fraction comparison is a skill that makes the whole number system make sense.',
    'Start by finding the lightest. Then find the lightest of the remaining. Keep going.')],
  'Comparing fractions is comparing amounts. Common denominators make it straightforward.',10),
],

